# -*- coding: utf-8 -*-
"""pycograd: a small, readable reverse-mode autograd built on numpy and pyccolo.

Write ordinary numeric Python -- including ``numpy`` calls like ``np.exp``,
``np.dot``, ``np.sum`` and operators like ``@`` -- and get correct gradients.
``Var`` is the reverse-mode tape node; ``value_and_grad`` / ``grad`` wrap a
function to return gradients with the same pytree structure as its arguments.
"""
from importlib.metadata import PackageNotFoundError, version

from pycograd import random
from pycograd._typing import Operand, Tensor
from pycograd.ad_graph import jit
from pycograd.backends import activate, device, get_backend
from pycograd.capture import Graph, capture, eval_graph
from pycograd.checkpoint import checkpoint
from pycograd.compile import compile_to
from pycograd.cost import (
    DEFAULT_COST_MODEL,
    CostModel,
    GraphCost,
    NodeCost,
    calibrate,
    cost_report,
)
from pycograd.data import DataLoader, batches
from pycograd.dtypes import current_dtype, dtype, resolve_dtype
from pycograd.export import export_onnx, export_torchscript, to_torch_module
from pycograd.extension import load_ipython_extension, unload_ipython_extension
from pycograd.functional import (
    avg_pool2d,
    batch_norm,
    batch_norm_init,
    causal_conv1d,
    conv1d,
    conv2d,
    conv_transpose1d,
    conv_transpose2d,
    cross_entropy,
    dropout,
    elu,
    embedding,
    gelu,
    group_norm,
    hardsigmoid,
    hardswish,
    instance_norm,
    layer_norm,
    leaky_relu,
    linear,
    log_softmax,
    logsumexp,
    max_pool2d,
    mish,
    multi_head_attention,
    one_hot,
    relu,
    rms_norm,
    scaled_dot_product_attention,
    selu,
    sigmoid,
    silu,
    softmax,
    softplus,
    softsign,
    streaming_conv1d,
    streaming_conv1d_init,
    streaming_conv2d,
    streaming_conv2d_init,
    streaming_conv_transpose1d,
    streaming_conv_transpose1d_init,
    streaming_conv_transpose2d,
    streaming_conv_transpose2d_init,
    swish,
    tanh,
    upsample_nearest2d,
)
from pycograd.ops import (
    AutodiffWarning,
    d_abs,
    d_arccos,
    d_arccosh,
    d_arcsin,
    d_arcsinh,
    d_arctan,
    d_arctanh,
    d_ceil,
    d_clip,
    d_column_stack,
    d_concatenate,
    d_cos,
    d_cosh,
    d_cumsum,
    d_deg2rad,
    d_dstack,
    d_einsum,
    d_exp,
    d_exp2,
    d_expand_dims,
    d_expm1,
    d_floor,
    d_gated_act,
    d_hstack,
    d_log,
    d_log1p,
    d_log2,
    d_log10,
    d_logsumexp,
    d_max,
    d_maximum,
    d_mean,
    d_min,
    d_minimum,
    d_rad2deg,
    d_reciprocal,
    d_reshape,
    d_sigmoid,
    d_sign,
    d_sin,
    d_sinh,
    d_softmax,
    d_sqrt,
    d_square,
    d_stack,
    d_std,
    d_sum,
    d_tan,
    d_tanh,
    d_transpose,
    d_var,
    d_vstack,
    d_where,
)
from pycograd.optimizers import (
    SGD,
    Adam,
    AdamW,
    Optimizer,
    clip_grad_norm,
    constant_lr,
    cosine_decay,
    step_decay,
)
from pycograd.params import (
    Param,
    ParamDict,
    Weight,
    buffer,
    frozen,
    on_cpu,
    on_device,
    param_values,
    params,
    register_pipescript_params_macro,
    tied,
)
from pycograd.passes import optimize
from pycograd.remat import (
    Decision,
    RematPlan,
    apply_remat_plan,
    eval_scheduled,
    plan_remat,
)
from pycograd.shapes import (
    Dim,
    ShapedArray,
    ShapeDtypeStruct,
    ShapeError,
    Summary,
    bind,
    eval_shape,
    infer_shapes,
    substitute,
    summary,
)
from pycograd.tensor import Var, detach
from pycograd.tracer import AutodiffTracer, resolve_call
from pycograd.training import accuracy, fit, train
from pycograd.transforms import (
    egrad,
    elementwise_grad,
    grad,
    gradient_descent,
    hessian,
    holomorphic_grad,
    jacfwd,
    jacobian,
    jacrev,
    jvp,
    make_jvp,
    make_vjp,
    value_and_grad,
    vmap,
)
from pycograd.tree import (
    sgd_update,
    tree_flatten,
    tree_leaves,
    tree_map,
    tree_structure,
    tree_unflatten,
)

# Friendly aliases for the fused primitives (also reached via ``np.einsum`` / ``np.cumsum``
# interception); these read more naturally than the ``d_`` names at a call site.
einsum = d_einsum
cumsum = d_cumsum
gated_act = d_gated_act  # tanh(f) * sigmoid(s), the WaveNet / GLU gate

try:
    __version__ = version("pycograd")
except PackageNotFoundError:  # not installed (e.g. running from a source checkout)
    __version__ = "0.0.0+unknown"

__all__ = [
    "__version__",
    # core
    "Var",
    "detach",
    "Tensor",
    "Operand",
    # parameters
    "Param",
    "ParamDict",
    "Weight",
    "frozen",
    "buffer",
    "tied",
    "on_cpu",
    "on_device",
    "params",
    "param_values",
    # transforms / training
    "value_and_grad",
    "grad",
    "checkpoint",
    "vmap",
    "jvp",
    "jacfwd",
    "jacrev",
    "jacobian",
    "hessian",
    "holomorphic_grad",
    "elementwise_grad",
    "egrad",
    "make_jvp",
    "make_vjp",
    "gradient_descent",
    "sgd_update",
    "train",
    "fit",
    "accuracy",
    # shape inference
    "eval_shape",
    "infer_shapes",
    "substitute",
    "bind",
    "summary",
    "Summary",
    "ShapeDtypeStruct",
    "ShapedArray",
    "ShapeError",
    "Dim",
    # compile to other frameworks (torch / tf / jax)
    "compile_to",
    "get_backend",
    # graph-capture IR + optimization passes
    "capture",
    "eval_graph",
    "optimize",
    "jit",
    "Graph",
    # static cost model over the capture IR (CPU / memory / disk)
    "cost_report",
    "CostModel",
    "GraphCost",
    "NodeCost",
    "DEFAULT_COST_MODEL",
    "calibrate",
    # rematerialization / spill planning + memory-managed execution
    "plan_remat",
    "RematPlan",
    "Decision",
    "apply_remat_plan",
    "eval_scheduled",
    # device / array backend seam (numpy default, cupy for GPU)
    "device",
    "activate",
    # working-dtype seam (float64 default; float32 / float16 / bfloat16)
    "dtype",
    "current_dtype",
    "resolve_dtype",
    # static export (standalone artifacts)
    "to_torch_module",
    "export_torchscript",
    "export_onnx",
    # optimizers
    "Optimizer",
    "SGD",
    "Adam",
    "AdamW",
    "clip_grad_norm",
    "constant_lr",
    "step_decay",
    "cosine_decay",
    # neural-net ops (stable softmax family, cross-entropy, activations)
    "softmax",
    "log_softmax",
    "logsumexp",
    "cross_entropy",
    "relu",
    "sigmoid",
    "silu",
    "swish",
    "gelu",
    "tanh",
    "leaky_relu",
    "elu",
    "softplus",
    "mish",
    "hardswish",
    "hardsigmoid",
    "softsign",
    "selu",
    "conv1d",
    "conv2d",
    "causal_conv1d",
    "conv_transpose1d",
    "conv_transpose2d",
    "streaming_conv1d",
    "streaming_conv1d_init",
    "streaming_conv2d",
    "streaming_conv2d_init",
    "streaming_conv_transpose1d",
    "streaming_conv_transpose1d_init",
    "streaming_conv_transpose2d",
    "streaming_conv_transpose2d_init",
    "upsample_nearest2d",
    "max_pool2d",
    "avg_pool2d",
    "one_hot",
    # neural-net layers (normalization, attention, embedding, linear, dropout)
    "layer_norm",
    "rms_norm",
    "batch_norm",
    "batch_norm_init",
    "group_norm",
    "instance_norm",
    "scaled_dot_product_attention",
    "multi_head_attention",
    "embedding",
    "linear",
    "dropout",
    # splittable PRNG keys (pycograd.random: key / split / fold_in + samplers)
    "random",
    # data / batching
    "batches",
    "DataLoader",
    # pytrees
    "tree_flatten",
    "tree_unflatten",
    "tree_leaves",
    "tree_structure",
    "tree_map",
    # tracer / interception
    "AutodiffTracer",
    "resolve_call",
    "AutodiffWarning",
    "register_pipescript_params_macro",
    # ipython / jupyter extension
    "load_ipython_extension",
    "unload_ipython_extension",
    # differentiable primitives
    "d_exp",
    "d_log",
    "d_sin",
    "d_cos",
    "d_tanh",
    "d_sqrt",
    "d_sigmoid",
    "d_abs",
    "d_square",
    "d_sinh",
    "d_cosh",
    "d_arctan",
    "d_tan",
    "d_arcsin",
    "d_arccos",
    "d_arctanh",
    "d_arcsinh",
    "d_arccosh",
    "d_exp2",
    "d_log2",
    "d_log10",
    "d_deg2rad",
    "d_rad2deg",
    "d_sign",
    "d_ceil",
    "d_floor",
    "d_log1p",
    "d_expm1",
    "d_reciprocal",
    "d_maximum",
    "d_minimum",
    "d_clip",
    "d_where",
    "d_sum",
    "d_mean",
    "d_var",
    "d_std",
    "d_max",
    "d_min",
    "d_softmax",
    "d_logsumexp",
    "d_concatenate",
    "d_transpose",
    "d_reshape",
    "d_expand_dims",
    "d_stack",
    "d_vstack",
    "d_hstack",
    "d_column_stack",
    "d_dstack",
    "d_einsum",
    "einsum",
    "d_cumsum",
    "cumsum",
    "d_gated_act",
    "gated_act",
]
