# -*- coding: utf-8 -*-
"""Skip registry for the ported op-coverage files (test_systematic.py, test_numpy.py).

Those two files are mechanical, byte-faithful ports of autograd's originals, so rather
than editing each test we centralize the gaps here and apply them in conftest via
``pytest_collection_modifyitems``. Each entry maps (filename, test name) -> skip reason.
Generated by triage (run, classify failures by error + op bucket); see REPORT.md."""

SKIPS = {
    (
        "test_numpy.py",
        "test_1d_array",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_1d_array_fanout",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_2d_array",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_2d_array_fanout",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_array_from_arrays",
    ): "pycograd-gap: np.array([...]) of Var/box leaves is not a differentiable constructor",
    (
        "test_numpy.py",
        "test_array_from_arrays_2",
    ): "pycograd-gap: np.array([...]) of Var/box leaves is not a differentiable constructor",
    (
        "test_numpy.py",
        "test_array_from_scalar",
    ): "pycograd-gap: np.array([...]) of Var/box leaves is not a differentiable constructor",
    (
        "test_numpy.py",
        "test_astype",
    ): "pycograd-gap: Var has no such ndarray method (e.g. .flatten()/.squeeze())",
    (
        "test_numpy.py",
        "test_c_",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_c_mixed",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_cast_to_int",
    ): "pycograd-gap: integer cast inside a traced function has no rule",
    (
        "test_numpy.py",
        "test_concatenate_axis_1_unnamed",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_cumsum_1d",
    ): "pycograd-gap: np.cumsum function form (the d_cumsum primitive exists but np.cumsum does not dispatch here)",
    (
        "test_numpy.py",
        "test_cumsum_no_axis",
    ): "pycograd-gap: np.cumsum function form (the d_cumsum primitive exists but np.cumsum does not dispatch here)",
    (
        "test_numpy.py",
        "test_diag",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_diagonal",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_dot_with_floats",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_numpy.py",
        "test_flatten_method",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_numpy.py", "test_fliplr"): "pycograd-gap: unsupported op (no autodiff rule)",
    ("test_numpy.py", "test_flipud"): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_gradient",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_len",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_linspace",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_make_diagonal",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_max_equal_values",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_max_equal_values_2d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_maximum_equal_values_2d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_mean_list_of_boxes",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_min_3_way_equality",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    ("test_numpy.py", "test_nan_to_num"): "pycograd-gap: no VJP rule for np.nan_to_num",
    (
        "test_numpy.py",
        "test_non_numpy_sum",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_outer",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    ("test_numpy.py", "test_prod_1"): "pycograd-gap: no VJP rule for np.prod",
    ("test_numpy.py", "test_prod_2"): "pycograd-gap: no VJP rule for np.prod",
    ("test_numpy.py", "test_prod_3"): "pycograd-gap: no VJP rule for np.prod",
    ("test_numpy.py", "test_prod_4"): "pycograd-gap: no VJP rule for np.prod",
    (
        "test_numpy.py",
        "test_r_basic",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_r_double",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_r_mixed",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_r_node_and_const",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_r_slicing",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_ravel_call",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_ravel_method",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_1d_axis0",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_axis0",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_axis0_rep1",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_axis1_rep1",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_roll",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_roll_no_axis",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_numpy.py", "test_rot90"): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_scalar_array_box_attributes",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_simple_append_arr",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_simple_append_list",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_simple_append_list_2D",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_squeeze_func",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_squeeze_method",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_std_list_of_boxes",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_tensordot_kwargs_by_position",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_numpy.py",
        "test_trace",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_numpy.py",
        "test_trace2",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_numpy.py",
        "test_trace_extradims",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_numpy.py",
        "test_tril",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_triu",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_var_list_of_boxes",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_systematic.py",
        "test_add",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_angle",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    ("test_systematic.py", "test_arccosh"): "pycograd-gap: no VJP rule for np.arccosh",
    ("test_systematic.py", "test_arcsinh"): "pycograd-gap: no VJP rule for np.arcsinh",
    ("test_systematic.py", "test_arctanh"): "pycograd-gap: no VJP rule for np.arctanh",
    (
        "test_systematic.py",
        "test_array_split_1d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_array_split_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_array_split_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_atleast_1d",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_atleast_2d",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_atleast_3d",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_systematic.py", "test_ceil"): "pycograd-gap: no VJP rule for np.ceil",
    (
        "test_systematic.py",
        "test_column_stack_1d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_systematic.py",
        "test_conj",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_conjugate",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_cross",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    ("test_systematic.py", "test_deg2rad"): "pycograd-gap: no VJP rule for np.deg2rad",
    ("test_systematic.py", "test_degrees"): "pycograd-gap: no VJP rule for np.degrees",
    (
        "test_systematic.py",
        "test_diag",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_diag_flat",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_diff",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_dot",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_dsplit_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_einsum2_covsum",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_matmult",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_matmult_broadcast",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_three_args",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_transpose",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum_three_args",
    ): "pycograd-gap: np.einsum with >=3 operands has no VJP rule",
    ("test_systematic.py", "test_exp2"): "pycograd-gap: no VJP rule for np.exp2",
    ("test_systematic.py", "test_fabs"): "pycograd-gap: no VJP rule for np.fabs",
    ("test_systematic.py", "test_floor"): "pycograd-gap: no VJP rule for np.floor",
    (
        "test_systematic.py",
        "test_fmax",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_fmin",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_gradient",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_hsplit_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_hsplit_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_hstack_1d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_systematic.py",
        "test_imag",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_inner",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_kron",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    ("test_systematic.py", "test_log10"): "pycograd-gap: no VJP rule for np.log10",
    ("test_systematic.py", "test_log2"): "pycograd-gap: no VJP rule for np.log2",
    (
        "test_systematic.py",
        "test_logaddexp",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_logaddexp2",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_matmul",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_mod",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_mod_neg",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_moveaxis",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_op_add",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_op_mod",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_op_mod_neg",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_op_mul",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_op_sub",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_outer",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_pad",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_partition",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_systematic.py", "test_prod"): "pycograd-gap: no VJP rule for np.prod",
    ("test_systematic.py", "test_rad2deg"): "pycograd-gap: no VJP rule for np.rad2deg",
    ("test_systematic.py", "test_radians"): "pycograd-gap: no VJP rule for np.radians",
    (
        "test_systematic.py",
        "test_real",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_real_ic",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_remainder",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_repeat",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_rollaxis",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_row_stack_1d",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_systematic.py",
        "test_row_stack_2d",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_systematic.py",
        "test_select",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_systematic.py", "test_sign"): "pycograd-gap: no VJP rule for np.sign",
    (
        "test_systematic.py",
        "test_sort",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_split_1d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_split_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_split_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_std",
    ): "pycograd-gap: np.std gradient mismatch under this check (reduction with ddof/sqrt)",
    (
        "test_systematic.py",
        "test_swapaxes",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_systematic.py", "test_tan"): "pycograd-gap: no VJP rule for np.tan",
    (
        "test_systematic.py",
        "test_tensordot_1",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tensordot_2",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tensordot_3",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tensordot_4",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tensordot_5",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tensordot_6",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tensordot_7",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tensordot_8",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tile",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_trace",
    ): "pycograd-gap: no VJP rule for general tensor contraction (np.dot/inner/outer/tensordot/kron/cross/trace/matmul)",
    (
        "test_systematic.py",
        "test_tril",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_tril_3d",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_triu",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_triu_3d",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_true_divide",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_true_divide_neg",
    ): "pycograd-gap: arithmetic via the numpy *function* form (np.add/multiply/divide/...) or forward-mode (jvp) of a two-tracer bilinear op is unsupported (the operator form works in reverse)",
    (
        "test_systematic.py",
        "test_vsplit_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_vsplit_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
}
