# -*- coding: utf-8 -*-
"""Skip registry for the ported op-coverage files (test_systematic.py, test_numpy.py).

Byte-faithful ports: gaps centralized here, applied in conftest via pytest_collection_modifyitems.
(filename, test name) -> skip reason. Regenerated by triage; see REPORT.md."""

SKIPS = {
    (
        "test_numpy.py",
        "test_1d_array",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_1d_array_fanout",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_2d_array",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_2d_array_fanout",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_array_from_arrays",
    ): "pycograd-gap: np.array([...]) of Var/box leaves is not a differentiable constructor",
    (
        "test_numpy.py",
        "test_array_from_arrays_2",
    ): "pycograd-gap: np.array([...]) of Var/box leaves is not a differentiable constructor",
    (
        "test_numpy.py",
        "test_array_from_scalar",
    ): "pycograd-gap: np.array([...]) of Var/box leaves is not a differentiable constructor",
    (
        "test_numpy.py",
        "test_astype",
    ): "pycograd-gap: Var has no such ndarray method (e.g. .flatten()/.squeeze())",
    (
        "test_numpy.py",
        "test_c_",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_c_mixed",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_cast_to_int",
    ): "pycograd-gap: integer cast inside a traced function has no rule",
    (
        "test_numpy.py",
        "test_concatenate_axis_1_unnamed",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_cumsum_1d",
    ): "pycograd-gap: np.cumsum function form does not dispatch to the d_cumsum rule",
    (
        "test_numpy.py",
        "test_cumsum_no_axis",
    ): "pycograd-gap: np.cumsum function form does not dispatch to the d_cumsum rule",
    (
        "test_numpy.py",
        "test_diag",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_diagonal",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_dot_with_floats",
    ): "pycograd-gap: np.dot with python-float operands in this autograd test (NameError in the ported body)",
    (
        "test_numpy.py",
        "test_flatten_method",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_numpy.py", "test_fliplr"): "pycograd-gap: unsupported op (no autodiff rule)",
    ("test_numpy.py", "test_flipud"): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_gradient",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_len",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_linspace",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_make_diagonal",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_max_equal_values",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_max_equal_values_2d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_maximum_equal_values_2d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_mean_list_of_boxes",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_min_3_way_equality",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    ("test_numpy.py", "test_nan_to_num"): "pycograd-gap: no VJP rule for np.nan_to_num",
    (
        "test_numpy.py",
        "test_non_numpy_sum",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_outer",
    ): "pycograd-gap: np.outer (deferred; needs a flatten+einsum lowering with an abstract-reshape path)",
    (
        "test_numpy.py",
        "test_r_basic",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_r_double",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_r_mixed",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_r_node_and_const",
    ): "pycograd-gap: tie/shape handling differs (e.g. equal-value max/min argmax tie-break)",
    (
        "test_numpy.py",
        "test_r_slicing",
    ): "pycograd-gap: gradient mismatch under check_grads (forward-mode or unsupported op semantics)",
    (
        "test_numpy.py",
        "test_ravel_call",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_ravel_method",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_1d_axis0",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_axis0",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_axis0_rep1",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_repeat_axis1_rep1",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_roll",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_roll_no_axis",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    ("test_numpy.py", "test_rot90"): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_scalar_array_box_attributes",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_simple_append_arr",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_simple_append_list",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_simple_append_list_2D",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_squeeze_func",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_squeeze_method",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_numpy.py",
        "test_std_list_of_boxes",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_numpy.py",
        "test_trace",
    ): "pycograd-gap: np.trace needs a diagonal einsum ('ii->'), which einsum rejects (repeated label within one operand)",
    (
        "test_numpy.py",
        "test_trace2",
    ): "pycograd-gap: np.trace needs a diagonal einsum ('ii->'), which einsum rejects (repeated label within one operand)",
    (
        "test_numpy.py",
        "test_trace_extradims",
    ): "pycograd-gap: np.trace needs a diagonal einsum ('ii->'), which einsum rejects (repeated label within one operand)",
    (
        "test_numpy.py",
        "test_tril",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_triu",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_numpy.py",
        "test_var_list_of_boxes",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_systematic.py",
        "test_angle",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_array_split_1d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_array_split_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_array_split_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_atleast_1d",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_atleast_2d",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_atleast_3d",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_column_stack_1d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_systematic.py",
        "test_conj",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_conjugate",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_cross",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_systematic.py",
        "test_diag",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_diag_flat",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_diff",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_dsplit_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_einsum2_covsum",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_matmult",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_matmult_broadcast",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_three_args",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum2_transpose",
    ): "pycograd-gap: np.einsum explicit-axes (operand-index tuple) form unsupported (recurses)",
    (
        "test_systematic.py",
        "test_einsum_three_args",
    ): "pycograd-gap: np.einsum with >=3 operands has no VJP rule",
    (
        "test_systematic.py",
        "test_fmax",
    ): "pycograd-gap: no rule for np.logaddexp/logaddexp2/fmax/fmin",
    (
        "test_systematic.py",
        "test_fmin",
    ): "pycograd-gap: no rule for np.logaddexp/logaddexp2/fmax/fmin",
    (
        "test_systematic.py",
        "test_gradient",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_hsplit_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_hsplit_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_hstack_1d",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_systematic.py",
        "test_imag",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    ("test_systematic.py", "test_kron"): "pycograd-gap: no VJP rule for np.kron",
    (
        "test_systematic.py",
        "test_logaddexp",
    ): "pycograd-gap: no rule for np.logaddexp/logaddexp2/fmax/fmin",
    (
        "test_systematic.py",
        "test_logaddexp2",
    ): "pycograd-gap: no rule for np.logaddexp/logaddexp2/fmax/fmin",
    (
        "test_systematic.py",
        "test_matmul",
    ): "pycograd-gap: general np.matmul over these shapes (broadcast/complex) is shape-limited",
    (
        "test_systematic.py",
        "test_moveaxis",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_outer",
    ): "pycograd-gap: np.outer (deferred; needs a flatten+einsum lowering with an abstract-reshape path)",
    (
        "test_systematic.py",
        "test_pad",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_partition",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_real",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_real_ic",
    ): "pycograd-gap: complex-number op (real/imag/conj/angle) -- pycograd is real-only",
    (
        "test_systematic.py",
        "test_repeat",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_rollaxis",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_row_stack_1d",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_systematic.py",
        "test_row_stack_2d",
    ): "pycograd-gap: forward-mode (jvp) of a two-tracer op, or an unsupported numpy-function form",
    (
        "test_systematic.py",
        "test_select",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_sort",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_split_1d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_split_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_split_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_std",
    ): "pycograd-gap: np.std gradient mismatch under this check (reduction with ddof/sqrt)",
    (
        "test_systematic.py",
        "test_swapaxes",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_tile",
    ): "pycograd-gap: no VJP rule for this array-manipulation op (repeat/tile/diff/gradient/roll/moveaxis/swapaxes/rollaxis/pad/select/sort/partition/atleast/squeeze/ravel/flatten/append)",
    (
        "test_systematic.py",
        "test_trace",
    ): "pycograd-gap: np.trace needs a diagonal einsum ('ii->'), which einsum rejects (repeated label within one operand)",
    (
        "test_systematic.py",
        "test_tril",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_tril_3d",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_triu",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_triu_3d",
    ): "pycograd-gap: no VJP rule for np.tril/np.triu/np.diag",
    (
        "test_systematic.py",
        "test_vsplit_2d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
    (
        "test_systematic.py",
        "test_vsplit_3d",
    ): "pycograd-gap: no VJP rule for the np.split family (split/vsplit/hsplit/dsplit/array_split)",
}
