# -*- coding: utf-8 -*-
"""Skip registry for the ported op-coverage files (test_systematic.py, test_numpy.py).

Byte-faithful ports: gaps centralized here, applied in conftest via pytest_collection_modifyitems.
(filename, test name) -> skip reason. Regenerated by triage; see REPORT.md."""

SKIPS = {
    (
        "test_numpy.py",
        "test_astype",
    ): "pycograd-design: `.astype` IS supported (ops.d_astype: graph-differentiable cast, see test_dtypes.py::test_astype_*). This test asserts the autograd convention that the eager grad follows the float32 *input array*'s dtype; pycograd instead follows the ambient working dtype (float64 by default) -- use `with pg.dtype('float32')`.",
    (
        "test_numpy.py",
        "test_cast_to_int",
    ): "pycograd-design: casts an intermediate to int64 (`np.int64(W[:, -1])`) and uses it as a fancy index. A pycograd `Var` holds real-valued tensors only (resolve_dtype rejects ints), so an in-trace int cast has no tape representation -- distinct from the float `.astype` cast, which is supported (ops.d_astype).",
    (
        "test_numpy.py",
        "test_diagonal",
    ): "pycograd-gap: np.diagonal with non-default axes + autograd's make_diagonal helper",
    (
        "test_numpy.py",
        "test_make_diagonal",
    ): "autograd-internal: np.make_diagonal is autograd-specific (not a numpy function)",
    (
        "test_numpy.py",
        "test_simple_append_list",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_numpy.py",
        "test_simple_append_list_2D",
    ): "pycograd-gap: unsupported op (no autodiff rule)",
    (
        "test_systematic.py",
        "test_einsum2_three_args",
    ): "pycograd-gap: einsum with a repeated label within one operand (a diagonal/trace inside einsum); the reverse einsum can't scatter to a diagonal",
    (
        "test_systematic.py",
        "test_einsum_three_args",
    ): "pycograd-gap: einsum with a repeated label within one operand (a diagonal/trace inside einsum); the reverse einsum can't scatter to a diagonal",
    (
        "test_systematic.py",
        "test_matmul",
    ): "pycograd-gap: general np.matmul over these shapes (broadcast/complex) is shape-limited",
    (
        "test_systematic.py",
        "test_std",
    ): "pycograd-gap: np.std gradient mismatch under this check (reduction with ddof/sqrt)",
}
